// Generated by CoffeeScript 1.3.1
(function() {
  var addLinkListeners, cacheImage, handleZoom, init;

  init = function() {
    console.log("loaded");
    window.zoom = new Zoom("z");
    return addLinkListeners();
  };

  addLinkListeners = function() {
    var a, fileTypes, type, _i, _len, _ref, _results;
    fileTypes = [".jpg", ".png", ".gif", ".jpeg", ".bmp", ".tiff", ".webm"];
    _ref = document.getElementsByTagName("a");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      a = _ref[_i];
      _results.push((function() {
        var _j, _len1, _results1;
        _results1 = [];
        for (_j = 0, _len1 = fileTypes.length; _j < _len1; _j++) {
          type = fileTypes[_j];
          if (a.getAttribute("href").match(type)) {
            if (a.childNodes.length !== 0 && a.firstChild === a.getElementsByTagName("img")[0]) {
              a.addEventListener("mouseover", cacheImage, false);
              _results1.push(a.addEventListener("click", handleZoom, false));
            } else {
              _results1.push(void 0);
            }
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  };

  handleZoom = function(e) {
    var image,
      _this = this;
    e.preventDefault();
    if (this.loaded) {
      return window.zoom.zoom(this);
    } else {
      window.zoom.showLoadingIndicator();
      image = document.createElement("img");
      image.onload = function() {
        _this.loaded = true;
        window.zoom.cache[image.src] = image;
        window.zoom.hideLoadingIndicator();
        return window.zoom.zoom(_this);
      };
      return image.src = this.getAttribute("href");
    }
  };

  cacheImage = function(e) {
    var image, url,
      _this = this;
    image = document.createElement("img");
    url = this.getAttribute("href");
    image.onload = function() {
      _this.loaded = true;
      window.zoom.cache[url] = image;
      return _this.removeEventListener("mouseover", cacheImage, false);
    };
    return image.src = url;
  };

  window.addEventListener("DOMContentLoaded", init, false);

}).call(this);
